testProject/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace testProject.Models
{
    public class Category
    {
        //One category to many Products

         //For Category ID
        [Key,ScaffoldColumn(false)]
        public int CategoryID { get; set; }


        //labelled for CategoryName
        [Required, StringLength(255), Display(Name ="Name")]
        public string CategoryName { get; set; }


        // labelled For Category Description
        [StringLength(int.MaxValue), Display(Name ="Description")]
        public string CategoryDescription { get; set; }

        //for one Category have many Products
        public virtual ICollection<Product> Products { get; set; }

       
    }
} 

testProject/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using testProject.Models;
//including this for the extra Project definition
using testProject.Models.ViewModels;
using System.Diagnostics;
//Reference: As per Christine's Code
namespace testProject.Controllers
{
    public class CategoryController : Controller
    {
        // variables which holds our database
        private ProductCMSContext db = new ProductCMSContext();

        // GET: Category
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

       
        // GET: Category New
        public ActionResult New()
        {
            CategoryEdit categoryeditview = new CategoryEdit();
            return View(categoryeditview);
        }

        // POST: Category New

        [HttpPost]
        public ActionResult New(string CategoryName_New, string CategoryDescription_New)
        {
            // Standard query representation for Categories to Add a new Category 
            string query = "insert into categories (CategoryName, CategoryDescription) values (@name, @description)";

            SqlParameter[] myparams = new SqlParameter[2];
            myparams[0] = new SqlParameter("@name", CategoryName_New);
            myparams[1] = new SqlParameter("@description", CategoryDescription_New);
          
           
            // By Using, This Command puts that Informtion into Database
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }


        // GET: Category Edit
        public ActionResult Edit(int id)
        {
           

            CategoryEdit categoryeditview = new CategoryEdit();

            // Line equivalent to "Select * from Categories where categoryid = .."
            // It will find one particular CategoryID form Database 
            categoryeditview.category = db.Categories.Find(id);

            //and it returns a view of Edit Category
            return View(categoryeditview);
        }


        // POST: Category Edit
        [HttpPost]
        public ActionResult Edit(int id, string CategoryName, string CategoryDescription)
        {
            //If the ID doesn't exist or the Category doesn't exist
            if ((id == null) || (db.Categories.Find(id) == null))
            {
                return HttpNotFound();

            }

            // update query for List of Categories
            string query = "update categories set CategoryName=@name, CategoryDescription=@description where categoryid=@id";
            SqlParameter[] myparams = new SqlParameter[3];
            myparams[0] = new SqlParameter("@name", CategoryName);
            myparams[1] = new SqlParameter("@description", CategoryDescription);
            myparams[2] = new SqlParameter("@id", id);
           
            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("Show/" + id);
        }


        // Show Category
        public ActionResult Show(int? id)
        {
            //If the ID doesn't exist or the Category doesn't exist
            if ((id == null) || (db.Categories.Find(id) == null))
            {
                return HttpNotFound();

            }

            // query to show the List of all categories 
            string query = "select * from categories where categoryid=@id";
            
            //Could also just pass the sqlparameter by itself instead of making an array of 1 item
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            //Hey view.. here's a list of all the categories in my db
            Category mycategory = db.Categories.SqlQuery(query, myparams).FirstOrDefault();

            return View(mycategory);
        }


        // Delete a Category
        public ActionResult Delete(int? id)
        {
            if ((id == null) || (db.Categories.Find(id) == null))
            {
                return HttpNotFound();

            }
            

            // to delete associated Products
            string query = "delete from Products where category_CategoryID=@id";
            SqlParameter param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            // to delete Category
            query = "delete from Categories where categoryid=@id";
            param = new SqlParameter("@id", id);
            db.Database.ExecuteSqlCommand(query, param);

            return RedirectToAction("List");
        }


        // List of Categories
        public ActionResult List()
        {
            // This function needs to print out a list of the categories

            IEnumerable<Category> categories = db.Categories.ToList();
            return View(categories);
        }
    }
}

testProject/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using testProject.Models;
//including this for the extra Project definition
using testProject.Models.ViewModels;
using System.Diagnostics;

//Reference: As per Christine's Code
namespace testProject.Controllers
{
    public class ProductController : Controller
    {
        //variable which holds our Database

        private ProductCMSContext db = new ProductCMSContext();
        
        
        // GET: Product
        public ActionResult Index()
        {
            // It redirect to the list view method for the Product
            return RedirectToAction("List");
        }
        
        // GET: New Product
        public ActionResult New()
        {
            return View(db.Categories.ToList());
        }

        // POST: New Product
        [HttpPost]
        public ActionResult New(string ProductName_New, string ProductDescription_New, float ProductPrice_New, int? ProductCategory_New) // Created a New variables for fields
        {
            // query to Add new Product with using CategoryID to select a Category for that particular Product
            string query = "insert into Products (ProductName, ProductDescription, ProductPrice, category_CategoryID) " +
                "values (@name,@description,@price,@cid)";

            SqlParameter[] myparams = new SqlParameter[4];
            myparams[0] = new SqlParameter("@name", ProductName_New);
            myparams[1] = new SqlParameter("@description", ProductDescription_New);
            myparams[2] = new SqlParameter("@price", ProductPrice_New);
            myparams[3] = new SqlParameter("@cid", ProductCategory_New);

            db.Database.ExecuteSqlCommand(query, myparams);
            
            return RedirectToAction("List");
        }

       
        // GET: Edit Product
        public ActionResult Edit(int? id)
        {
           
            ProductEdit productedit = new ProductEdit();
            productedit.product = db.Products.Find(id);
            productedit.categories = db.Categories.ToList();
            
            if (productedit.product != null) return View(productedit);
            else return HttpNotFound();
        }


        // POST: Edit Product
        [HttpPost]
        public ActionResult Edit(string ProductName, string ProductDescription, float? ProductPrice, int? ProductCategory, int? id)
        {
            //to find error 
            //Debug.WriteLine("");
            if ((id == null) || (db.Products.Find(id) == null))
            {
                return HttpNotFound();

            }
            // query to update a particular Product
            string query = "update products set productname=@name, " +
                "productdescription=@description, " +
                "productprice=@price, " +
                "category_CategoryID=@cid where productid = @id";

            SqlParameter[] myparams = new SqlParameter[5];

            myparams[0] = new SqlParameter();
            myparams[0].ParameterName = "@name";
            myparams[0].Value = ProductName;

            myparams[1] = new SqlParameter();
            myparams[1].ParameterName = "@description";
            myparams[1].Value = ProductDescription;

            myparams[2] = new SqlParameter();
            myparams[2].ParameterName = "@price";
            myparams[2].Value = ProductPrice;

            myparams[3] = new SqlParameter();
            myparams[3].ParameterName = "@cid";
            myparams[3].Value = ProductCategory;

            myparams[4] = new SqlParameter();
            myparams[4].ParameterName = "@id";
            myparams[4].Value = id;
            db.Database.ExecuteSqlCommand(query, myparams);
           

            return RedirectToAction("Show/" + id);
        }

        // Show Product
        public ActionResult Show(int id)
        {
            string query = "select * from products where productid =@id";

            //should return type of "Product"

            // debug used for to check error
            Debug.WriteLine(query);
            return View(db.Products.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }


        //Delete a Product
        public ActionResult Delete(int id)
        {
           
            // query to delete a particular Product 
            string query = "delete from Products where productid = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            return RedirectToAction("List");
        }


        //List of Product
        public ActionResult List()
        {

            //it returns view for List of Products
            return View(db.Products.ToList());

        }
    }
}

testProject/Views/Category/Edit.cshtml
@model testProject.Models.ViewModels.CategoryEdit
@{
    ViewBag.Title = "Edit";
}

<h2>Edit @Model.category.CategoryName</h2>


<form method="POST" action="/Category/Edit/@Model.category.CategoryID">
    <div>
        <label>Name</label>
        <input type="text" value="@Model.category.CategoryName" id="CategoryName" name="CategoryName" />
    </div>
    <br />
    <div>
        <div><b>Description</b></div>
        <textarea id="CategoryDescription" name="CategoryDescription">@Model.category.CategoryDescription</textarea>
    </div>
    <br />
    <br />
    <div>
        <input type="submit" value="Submit" />
    </div>
</form>

testProject/Views/Category/List.cshtml
@model IEnumerable<testProject.Models.Category>
@{
    ViewBag.Title = "List";
}

<h2>Category</h2>

<div>
    @Html.ActionLink("Add New Category", "New", "Category")
</div>
<br />
<br />
<div>
    @foreach (var category in Model)
    {
        <div>

            <div> <!--i was tryig to enter null value then it occured error then i figure it out from the given reference-->
                @if (!string.IsNullOrEmpty(category.CategoryName))
                {<!--I made changes bcoz of error which shows Null or Empty Value so, here Reference: https://www.codeproject.com/Questions/1201350/Value-cannot-be-null-or-empty-in-actionlink-->

                    <label>@Html.ActionLink(category.CategoryName, "Show/" + category.CategoryID)</label> }
                    <p>Total Products: @category.Products.Count()</p>
                    <p>@category.CategoryDescription</p>

                    <span>

                        @Html.ActionLink("Delete", "Delete/" + category.CategoryID)

                    </span>
                </div>
            <br />
            <hr />
        </div>

    }
</div>

testProject/Views/Category/New.cshtml
@model testProject.Models.ViewModels.CategoryEdit
@{
    ViewBag.Title = "New";
}

<h2>New Category</h2>


<form method="POST" action="/Category/New">
    <br />
    <br />
    <div>
        <label>Name:</label>
        <input id="CategoryName_New" name="CategoryName_New" />
    </div>
    <br />

    <div>
        <label>Description:</label>
        <textarea id="CategoryDescription_New" name="CategoryDescription_New"></textarea>
    </div>
    <br />
    <br />
    <div>
        <input type="submit" value="Submit" />
    </div>


</form>

testProject/Views/Category/Show.cshtml
@model testProject.Models.Category
@{
    ViewBag.Title = "Show";
}

<h2>Show @Model.CategoryName</h2>
<br />
<br />
<p><b>Description:</b></p>
<p>@Model.CategoryDescription</p>
<br />
<br />

<!--For Edit Category-->
<div>

    @Html.ActionLink("Edit", "Edit/" + Model.CategoryID)
</div>

<!--For Delete Category-->

<div>

    @Html.ActionLink("Delete", "Delete/" + Model.CategoryID)

</div>

<!--List of Products-->

<h3>Products in this Category</h3>

<!--Add a New Product-->

<br />

@foreach (var product in Model.Products)
{
<b> <span>@Html.ActionLink(product.ProductName, "Show/" + product.ProductID, "Product")</span> </b><br />
}

<br />
<br />
<p>
    @Html.ActionLink("Add A Product", "New/", "Product")
</p>